from __future__ import annotations

from .balldontlie_nba_connector import BallDontLieNBAConnector
from .billie_jean_king_cup_history_connector import BillieJeanKingCupHistoryConnector
from .biathlon_world_championships_history_connector import BiathlonWorldChampionshipsHistoryConnector
from .bwf_world_championships_history_connector import BwfWorldChampionshipsHistoryConnector
from .bwf_thomas_uber_cup_history_connector import BwfThomasUberCupHistoryConnector
from .davis_cup_history_connector import DavisCupHistoryConnector
from .fiba_basketball_world_cup_history_connector import FibaBasketballWorldCupHistoryConnector
from .fiba_ranking_history_connector import FibaRankingHistoryConnector
from .fih_hockey_world_cup_history_connector import FihHockeyWorldCupHistoryConnector
from .fih_world_ranking_history_connector import FihWorldRankingHistoryConnector
from .fie_world_championships_history_connector import FieWorldChampionshipsHistoryConnector
from .fei_world_championships_history_connector import FeiWorldChampionshipsHistoryConnector
from .fig_artistic_gymnastics_world_championships_history_connector import (
    FigArtisticGymnasticsWorldChampionshipsHistoryConnector,
)
from .fis_alpine_world_ski_championships_history_connector import FisAlpineWorldSkiChampionshipsHistoryConnector
from .fis_nordic_world_ski_championships_history_connector import FisNordicWorldSkiChampionshipsHistoryConnector
from .formulae_world_championship_history_connector import FormulaEWorldChampionshipHistoryConnector
from .formula1_world_championship_history_connector import Formula1WorldChampionshipHistoryConnector
from .fivb_volleyball_world_championship_history_connector import FivbVolleyballWorldChampionshipHistoryConnector
from .fifa_ranking_history_connector import FifaRankingHistoryConnector
from .fifa_beach_soccer_world_cup_history_connector import FifaBeachSoccerWorldCupHistoryConnector
from .fifa_futsal_world_cup_history_connector import FifaFutsalWorldCupHistoryConnector
from .fifa_women_ranking_history_connector import FifaWomenRankingHistoryConnector
from .fifa_women_world_cup_history_connector import FifaWomenWorldCupHistoryConnector
from .fide_chess_olympiad_history_connector import FideChessOlympiadHistoryConnector
from .football_data_connector import FootballDataConnector
from .ihf_handball_world_championship_history_connector import IhfHandballWorldChampionshipHistoryConnector
from .iihf_ice_hockey_world_championship_history_connector import (
    IihfIceHockeyWorldChampionshipHistoryConnector,
)
from .icf_canoe_world_championships_history_connector import IcfCanoeWorldChampionshipsHistoryConnector
from .ittf_world_table_tennis_championships_history_connector import IttfWorldTableTennisChampionshipsHistoryConnector
from .icc_team_ranking_history_connector import IccTeamRankingHistoryConnector
from .icc_cricket_world_cup_history_connector import IccCricketWorldCupHistoryConnector
from .olympics_keith_history_connector import OlympicsKeithHistoryConnector
from .paris_2024_summer_olympics_connector import Paris2024SummerOlympicsConnector
from .rugby_league_world_cup_history_connector import RugbyLeagueWorldCupHistoryConnector
from .rugby_world_cup_history_connector import RugbyWorldCupHistoryConnector
from .rugby_world_cup_sevens_history_connector import RugbyWorldCupSevensHistoryConnector
from .uci_road_cycling_major_competitions_history_connector import (
    UciRoadCyclingMajorCompetitionsHistoryConnector,
)
from .uci_road_nation_ranking_history_connector import UciRoadNationRankingHistoryConnector
from .uci_cyclocross_world_championships_history_connector import UciCyclocrossWorldChampionshipsHistoryConnector
from .uci_mountain_bike_world_championships_history_connector import UciMountainBikeWorldChampionshipsHistoryConnector
from .uci_track_cycling_world_championships_history_connector import (
    UciTrackCyclingWorldChampionshipsHistoryConnector,
)
from .wbsc_baseball_softball_world_championship_history_connector import (
    WbscBaseballSoftballWorldChampionshipHistoryConnector,
)
from .wikidata_connector import WikidataConnector
from .world_cup_history_connector import WorldCupHistoryConnector
from .world_athletics_championships_history_connector import WorldAthleticsChampionshipsHistoryConnector
from .world_aquatics_championships_history_connector import WorldAquaticsChampionshipsHistoryConnector
from .world_archery_championships_history_connector import WorldArcheryChampionshipsHistoryConnector
from .world_baseball_classic_history_connector import WorldBaseballClassicHistoryConnector
from .world_boxing_championships_history_connector import WorldBoxingChampionshipsHistoryConnector
from .world_curling_championships_history_connector import WorldCurlingChampionshipsHistoryConnector
from .world_amateur_team_championships_history_connector import WorldAmateurTeamChampionshipsHistoryConnector
from .world_figure_skating_championships_history_connector import WorldFigureSkatingChampionshipsHistoryConnector
from .world_games_history_connector import WorldGamesHistoryConnector
from .world_judo_championships_history_connector import WorldJudoChampionshipsHistoryConnector
from .world_karate_championships_history_connector import WorldKarateChampionshipsHistoryConnector
from .world_lacrosse_championship_history_connector import WorldLacrosseChampionshipHistoryConnector
from .world_lacrosse_womens_world_cup_history_connector import WorldLacrosseWomensWorldCupHistoryConnector
from .world_netball_cup_history_connector import WorldNetballCupHistoryConnector
from .world_rowing_championships_history_connector import WorldRowingChampionshipsHistoryConnector
from .world_sailing_championships_history_connector import WorldSailingChampionshipsHistoryConnector
from .world_taekwondo_championships_history_connector import WorldTaekwondoChampionshipsHistoryConnector
from .world_triathlon_championship_series_history_connector import WorldTriathlonChampionshipSeriesHistoryConnector
from .world_weightlifting_championships_history_connector import WorldWeightliftingChampionshipsHistoryConnector
from .world_wrestling_championships_history_connector import WorldWrestlingChampionshipsHistoryConnector
from .world_rugby_ranking_history_connector import WorldRugbyRankingHistoryConnector


CONNECTOR_REGISTRY = {
    "wikidata": WikidataConnector,
    "football_data": FootballDataConnector,
    "balldontlie_nba": BallDontLieNBAConnector,
    "billie_jean_king_cup_history": BillieJeanKingCupHistoryConnector,
    "biathlon_world_championships_history": BiathlonWorldChampionshipsHistoryConnector,
    "bwf_world_championships_history": BwfWorldChampionshipsHistoryConnector,
    "bwf_thomas_uber_cup_history": BwfThomasUberCupHistoryConnector,
    "davis_cup_history": DavisCupHistoryConnector,
    "ittf_world_table_tennis_championships_history": IttfWorldTableTennisChampionshipsHistoryConnector,
    "fiba_ranking_history": FibaRankingHistoryConnector,
    "fiba_basketball_world_cup_history": FibaBasketballWorldCupHistoryConnector,
    "fih_hockey_world_cup_history": FihHockeyWorldCupHistoryConnector,
    "fih_world_ranking_history": FihWorldRankingHistoryConnector,
    "fie_world_championships_history": FieWorldChampionshipsHistoryConnector,
    "fei_world_championships_history": FeiWorldChampionshipsHistoryConnector,
    "fig_artistic_gymnastics_world_championships_history": FigArtisticGymnasticsWorldChampionshipsHistoryConnector,
    "fis_alpine_world_ski_championships_history": FisAlpineWorldSkiChampionshipsHistoryConnector,
    "fis_nordic_world_ski_championships_history": FisNordicWorldSkiChampionshipsHistoryConnector,
    "formulae_world_championship_history": FormulaEWorldChampionshipHistoryConnector,
    "formula1_world_championship_history": Formula1WorldChampionshipHistoryConnector,
    "fivb_volleyball_world_championship_history": FivbVolleyballWorldChampionshipHistoryConnector,
    "fifa_ranking_history": FifaRankingHistoryConnector,
    "fifa_beach_soccer_world_cup_history": FifaBeachSoccerWorldCupHistoryConnector,
    "fifa_futsal_world_cup_history": FifaFutsalWorldCupHistoryConnector,
    "fifa_women_ranking_history": FifaWomenRankingHistoryConnector,
    "fifa_women_world_cup_history": FifaWomenWorldCupHistoryConnector,
    "fide_chess_olympiad_history": FideChessOlympiadHistoryConnector,
    "world_rugby_ranking_history": WorldRugbyRankingHistoryConnector,
    "rugby_league_world_cup_history": RugbyLeagueWorldCupHistoryConnector,
    "rugby_world_cup_history": RugbyWorldCupHistoryConnector,
    "rugby_world_cup_sevens_history": RugbyWorldCupSevensHistoryConnector,
    "uci_cyclocross_world_championships_history": UciCyclocrossWorldChampionshipsHistoryConnector,
    "uci_mountain_bike_world_championships_history": UciMountainBikeWorldChampionshipsHistoryConnector,
    "uci_road_cycling_major_competitions_history": UciRoadCyclingMajorCompetitionsHistoryConnector,
    "uci_road_nation_ranking_history": UciRoadNationRankingHistoryConnector,
    "uci_track_cycling_world_championships_history": UciTrackCyclingWorldChampionshipsHistoryConnector,
    "wbsc_baseball_softball_world_championship_history": WbscBaseballSoftballWorldChampionshipHistoryConnector,
    "ihf_handball_world_championship_history": IhfHandballWorldChampionshipHistoryConnector,
    "iihf_ice_hockey_world_championship_history": IihfIceHockeyWorldChampionshipHistoryConnector,
    "icf_canoe_world_championships_history": IcfCanoeWorldChampionshipsHistoryConnector,
    "icc_team_ranking_history": IccTeamRankingHistoryConnector,
    "icc_cricket_world_cup_history": IccCricketWorldCupHistoryConnector,
    "world_cup_history": WorldCupHistoryConnector,
    "world_athletics_championships_history": WorldAthleticsChampionshipsHistoryConnector,
    "world_aquatics_championships_history": WorldAquaticsChampionshipsHistoryConnector,
    "world_archery_championships_history": WorldArcheryChampionshipsHistoryConnector,
    "world_baseball_classic_history": WorldBaseballClassicHistoryConnector,
    "world_boxing_championships_history": WorldBoxingChampionshipsHistoryConnector,
    "world_curling_championships_history": WorldCurlingChampionshipsHistoryConnector,
    "world_amateur_team_championships_history": WorldAmateurTeamChampionshipsHistoryConnector,
    "world_figure_skating_championships_history": WorldFigureSkatingChampionshipsHistoryConnector,
    "world_games_history": WorldGamesHistoryConnector,
    "world_judo_championships_history": WorldJudoChampionshipsHistoryConnector,
    "world_karate_championships_history": WorldKarateChampionshipsHistoryConnector,
    "world_lacrosse_championship_history": WorldLacrosseChampionshipHistoryConnector,
    "world_lacrosse_womens_world_cup_history": WorldLacrosseWomensWorldCupHistoryConnector,
    "world_netball_cup_history": WorldNetballCupHistoryConnector,
    "world_rowing_championships_history": WorldRowingChampionshipsHistoryConnector,
    "world_sailing_championships_history": WorldSailingChampionshipsHistoryConnector,
    "world_taekwondo_championships_history": WorldTaekwondoChampionshipsHistoryConnector,
    "world_triathlon_championship_series_history": WorldTriathlonChampionshipSeriesHistoryConnector,
    "world_weightlifting_championships_history": WorldWeightliftingChampionshipsHistoryConnector,
    "world_wrestling_championships_history": WorldWrestlingChampionshipsHistoryConnector,
    "paris_2024_summer_olympics": Paris2024SummerOlympicsConnector,
    "olympics_keith_history": OlympicsKeithHistoryConnector,
}


def build_connector(connector_name: str):
    key = connector_name.strip().lower()
    if key not in CONNECTOR_REGISTRY:
        available = ", ".join(sorted(CONNECTOR_REGISTRY))
        raise ValueError(f"Unknown connector '{connector_name}'. Available: {available}")
    return CONNECTOR_REGISTRY[key]()
